# Generated by Django 4.1.4 on 2024-01-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
