# Generated by Django 5.0.1 on 2024-01-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_rename_customerprofile_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
