# Generated by Django 5.0.1 on 2024-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
