# Generated by Django 5.0.1 on 2024-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('productName', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='System.product')),
            ],
        ),
    ]
