# Generated by Django 5.0.1 on 2024-01-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
    ]
